// Generated by Viva Colombia compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int builtin_print(char* s) { printf("%s", s); return 0; }
int builtin_println(char* s) { printf("%s\n", s); return 0; }
void builtin_print_num(int n) { printf("%d", n); }
void builtin_println_num(int n) { printf("%d\n", n); }
void builtin_simon_bolivar() { printf("Simón Bolívar: Libertador de Colombia, Venezuela, Ecuador, Perú y Bolivia\n"); }
void builtin_francisco_narino() { printf("Francisco de Paula Santander y Nariño: Héroe de la independencia colombiana\n"); }
void builtin_maria_cano() { printf("María Cano: Líder obrera y feminista colombiana\n"); }
void builtin_jorge_eliecer_gaitan() { printf("Jorge Eliécer Gaitán: Líder político y defensor del pueblo colombiano\n"); }
void builtin_gabriel_garcia_marquez() { printf("Gabriel García Márquez: Nobel de Literatura, autor de Cien Años de Soledad\n"); }

int main() {
    builtin_println("x es mayor que 5");
    return 0;
}
