; Generated by Viva Colombia compiler
section .data
    fmt_print db "%s", 10, 0
    fmt_print_num db "%d", 10, 0
    str_simon db "Simón Bolívar: Libertador de Colombia, Venezuela, Ecuador, Perú y Bolivia", 10, 0
    str_francisco db "Francisco de Paula Santander y Nariño: Héroe de la independencia colombiana", 10, 0
    str_maria db "María Cano: Líder obrera y feminista colombiana", 10, 0
    str_jorge db "Jorge Eliécer Gaitán: Líder político y defensor del pueblo colombiano", 10, 0
    str_gabriel db "Gabriel García Márquez: Nobel de Literatura, autor de Cien Años de Soledad", 10, 0

section .text
    global main
    extern printf

main:
    push rbp
    mov rbp, rsp
        mov rdi, fmt_str
    mov rsi, str_0
    xor rax, rax
    call printf
    mov rax, 0
    pop rbp
    ret
