// Generated by Viva compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Builtin functions
int builtin_print(char* str) { printf("%s", str); return 0; }
int builtin_println(char* str) { printf("%s\n", str); return 0; }
void builtin_print_num(int num) { printf("%d", num); }
void builtin_println_num(int num) { printf("%d\n", num); }
void builtin_simon_bolivar() { printf("Simón Bolívar: Libertador de Colombia, Venezuela, Ecuador, Perú y Bolivia\n"); }
void builtin_francisco_narino() { printf("Francisco de Paula Santander y Nariño: Héroe de la independencia colombiana\n"); }
void builtin_maria_cano() { printf("María Cano: Líder obrera y feminista colombiana\n"); }
void builtin_jorge_eliecer_gaitan() { printf("Jorge Eliécer Gaitán: Líder político y defensor del pueblo colombiano\n"); }
void builtin_gabriel_garcia_marquez() { printf("Gabriel García Márquez: Nobel de Literatura, autor de Cien Años de Soledad\n"); }

// Program start
int main() {
    builtin_println("Hello from variable test!");
    return 0;
}
