// Generated by Viva Colombia compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

void prt(char* s){printf("%s",s);}
void prtln(char* s){printf("%s\n",s);}
void prtnum(int n){printf("%d",n);}
void prtlnnum(int n){printf("%d\n",n);}
void bolivar(){printf("Simon Bolivar: Libertador\n");}
void narino(){printf("Francisco Narino: Heroe\n");}
void cano(){printf("Maria Cano: Lider\n");}
void gaitan(){printf("Jorge Gaitan: Lider politico\n");}
void garcia(){printf("Gabriel Garcia Marquez: Nobel\n");}

int main() {
    prtln("=== Phase 6: File I/O ===");
    FILE* f;
    f = fopen("test_output.txt", "w");
    fprintf(f, "%s", "Hola desde Viva!");
    fclose(f);
    prtln("File written successfully");
    FILE* g;
    g = fopen("test_output.txt", "r");
    int contenido = 0;
    contenido = fgetc(g);
    fclose(g);
    prtln("File read back");
    prtln("=== Phase 6: Stdlib ===");
    int num = 42;
    int neg = (0 - 10);
    int absval = abs(neg);
    prtln("abs(-10) = ");
    prtlnnum(absval);
    int pot = (int)pow(2, 8);
    prtln("pow(2,8) = ");
    prtlnnum(pot);
    prtln("=== Phase 6 Complete ===");
    return 0;
}
