// Generated by Viva Colombia compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

void prt(char* s){printf("%s",s);}
void prtln(char* s){printf("%s\n",s);}
void prtnum(int n){printf("%d",n);}
void prtlnnum(int n){printf("%d\n",n);}
void bolivar(){printf("Simon Bolivar: Libertador\n");}
void narino(){printf("Francisco Narino: Heroe\n");}
void cano(){printf("Maria Cano: Lider\n");}
void gaitan(){printf("Jorge Gaitan: Lider politico\n");}
void garcia(){printf("Gabriel Garcia Marquez: Nobel\n");}

int main() {
    prtln("=== Testing Basics ===");
    int x = 10;
    int y = 20;
    int z = (x + y);
    prtlnnum(z);
    prtln("=== Testing If ===");
    if ((x < y)) {
        prtln("x < y works!");
    }
    prtln("=== Testing While ===");
    int i = 1;
    while ((i < 4)) {
        prtlnnum(i);
        i = (i + 1);
    }
    prtln("=== Testing Heroes ===");
    bolivar();
    prtln("=== Done ===");
    return 0;
}
