// Generated by Viva Colombia compiler
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

void prt(char* s){printf("%s",s);}
void prtln(char* s){printf("%s\n",s);}
void prtnum(int n){printf("%d",n);}
void prtlnnum(int n){printf("%d\n",n);}
void bolivar(){printf("Simon Bolivar: Libertador\n");}
void narino(){printf("Francisco Narino: Heroe\n");}
void cano(){printf("Maria Cano: Lider\n");}
void gaitan(){printf("Jorge Gaitan: Lider politico\n");}
void garcia(){printf("Gabriel Garcia Marquez: Nobel\n");}

int main() {
    prtln("=== Phase 1-3: Basic Operations ===");
    int x = 10;
    int y = 20;
    int z = (x + y);
    prtln("x + y = ");
    prtlnnum(z);
    int suma = (5 + 3);
    int resta = (10 - 4);
    int mult = (6 * 7);
    int div = (100 / 5);
    prtln("5+3=");
    prtlnnum(suma);
    prtln("10-4=");
    prtlnnum(resta);
    prtln("6*7=");
    prtlnnum(mult);
    prtln("100/5=");
    prtlnnum(div);
    prtln("Hola Colombia!");
    prtln("Viva la patria!");
    prtln("=== Phase 5: Conditionals & Loops ===");
    int num = 15;
    if ((num > 10)) {
        prtln("num is greater than 10");
    } else {
        prtln("num is 10 or less");
    }
    prtln("Counting with mientras:");
    int contador = 1;
    prtlnnum(contador);
    contador = (contador + 1);
    int a = 5;
    int b = 10;
    if ((a < b)) {
        if ((a > 0)) {
            prtln("a is positive and less than b");
        }
    }
    prtln("=== Phase 5: Functions ===");
    sumar(p1, p2);
    int resultado = (p1 + p2);
    prtlnnum(resultado);
    factorial(n);
    prtlnnum(1);
    int f = 1;
    int i = 2;
    f = (f * i);
    i = (i + 1);
    prtlnnum(f);
    sumar(100, 200);
    prtln("Factorial of 5:");
    factorial(5);
    prtln("=== Colombian Heroes ===");
    bolivar();
    policarpa();
    prtln("=== All Basic Tests Complete ===");
    return 0;
}
